package userInterface;

/**
 * SlideUI is the main class for the user interface. It contains the menus and
 * the PuzzlePanel.
 *
 * @author Griffin
 */
public class SlideUI extends javax.swing.JFrame
{

    /**
     * Creates new form SlideUI
     */
    public SlideUI()
    {
        initComponents();
        setSize(500, 550);
    }

    /**
     * This method sets undoMenuItem either enabled or disabled.
     *
     * @param bool - True to set undoMenuItem enabled.
     */
    public void setUndoEnabled(boolean bool)
    {
        undoMenuItem.setEnabled(bool);
    }

    /**
     * Creates a VictoryPopup.
     */
    public void displayVictory()
    {
        VictoryPopup popup = new VictoryPopup();
        popup.setLocationRelativeTo(this);
        popup.setVisible(true);

    }

    /**
     * This instantiates a new PuzzlePanel, removes any old one, and adds the
     * new one to this form.
     *
     * @param x - the width of the board that is created by the new PuzzlePanel
     * @param y - the height of the board that is created by the new PuzzlePanel
     */
    void createPuzzle(int x, int y)
    {
        slide.Board board = new slide.Board(x, y);
        board.shuffle();
        if(puzPan != null)
            getContentPane().remove(puzPan);
        puzPan = (PuzzlePanel) getContentPane().add(new PuzzlePanel(this, board));
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newPuzzleMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("slide");

        menuBar.setName(""); // NOI18N

        fileMenu.setText("File");

        newPuzzleMenuItem.setLabel("New Puzzle");
        newPuzzleMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newPuzzleMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newPuzzleMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        undoMenuItem.setEnabled(false);
        undoMenuItem.setLabel("Undo");
        undoMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                undoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(undoMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This creates a new NewPuzzleWindow.
     * 
     * @param evt - unused
     */
    private void newPuzzleMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newPuzzleMenuItemActionPerformed
    {//GEN-HEADEREND:event_newPuzzleMenuItemActionPerformed
        NewPuzzleWindow newPuzzleWindow = new NewPuzzleWindow(this);
        newPuzzleWindow.setVisible(true);
        newPuzzleWindow.setLocationRelativeTo(this);
    }//GEN-LAST:event_newPuzzleMenuItemActionPerformed

    /**
     * Undoes a move on the current puzzle.
     * 
     * @param evt 
     */
    private void undoMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_undoMenuItemActionPerformed
    {//GEN-HEADEREND:event_undoMenuItemActionPerformed
        puzPan.undo();
    }//GEN-LAST:event_undoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SlideUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(()
                -> 
                {
                    SlideUI ui = new SlideUI();
                    ui.setVisible(true);
                    ui.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newPuzzleMenuItem;
    private javax.swing.JMenuItem undoMenuItem;
    // End of variables declaration//GEN-END:variables
    /**
     * The current puzzle.
     */
    private PuzzlePanel puzPan;
}
